import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Metadata } from "next";
import React from "react";
import AdminSidebar from "../_components/admin-sidebar";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Mint - Admin Area",
  description: "Generated by create next app",
};

async function RoutesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AdminSidebar />
      <div className="min-h-screen">
        <SidebarTrigger />
        {children}
      </div>
    </SidebarProvider>
  );
}

export default RoutesLayout;

/**
 * 
 * Dashboard
 * Projects
 * Categories
 * Products
 * Merchant
//  * Colors
//  * Sizes
  * Settings
  * Orders
  * Users
 */
