import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Mint - Admin Area",
  description: "Generated by create next app",
};

function RoutesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="min-h-screen">{children}</div>;
}

export default RoutesLayout;


/**
 * 
 * Dashboard
 * Projects
 * Categories
 * Products
 * Merchant
//  * Colors
//  * Sizes
  * Settings
  * Orders
  * Users
 */ 
